# TASCA 2-A

## NIVELL 1

### *Exercici 1*

* Crea un np.array d'una dimensió, que inclogui l'almenys 8 nombres sencers, data type int64. Mostra la dimensió i la forma de la matriu. 

In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8], dtype = 'int64')

In [3]:
arr.dtype

dtype('int64')

In [4]:
arr.ndim

1

In [5]:
arr.shape

(8,)

### *Exercici 2*

* De la matriu de l'exercici 1, calcula el valor mitjà dels valors introduïts i resta la mitjana resultant de cada un dels valors de la matriu.

In [6]:
valor_mitja = np.mean(arr)

In [7]:
print(valor_mitja)

4.5


In [8]:
type(valor_mitja)

numpy.float64

In [9]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int64)

In [10]:
for x in arr:
    print(x - valor_mitja)
    

-3.5
-2.5
-1.5
-0.5
0.5
1.5
2.5
3.5


### *Exercici 3*

* Crea una matriu bidimensional amb una forma de 5 x 5. Extreu el valor màxim de la matriu, i els valors màxims de cadascun dels seus eixos.

In [11]:
from numpy import random
x = random.randint(100, size=(5, 5))

In [12]:
x

array([[66, 64, 39, 70, 11],
       [61, 99, 82, 39, 84],
       [82,  7, 27,  2, 83],
       [59, 43, 40, 73, 12],
       [18, 39, 27, 49, 55]])

*Valor màxim de la matriu*

In [13]:
valor_maxim = x.max()
print('El valor màxim de la matriu és: {}'.format(valor_maxim))

El valor màxim de la matriu és: 99


*Valor màxim de cada fila de la matriu*

In [14]:
np.amax(x, axis = 1)

array([70, 99, 83, 73, 55])

*Valor màxim de cada columna de la matriu*

In [15]:
np.amax(x, axis = 0)

array([82, 99, 82, 73, 84])

### NIVELL 2

### *Exercici 4*

* Mostreu-me amb exemples de diferents matrius, la regla fonamental de Broadcasting que diu : "les matrius es poden transmetre / broadcast si les seves dimensions coincideixen o si una de les matrius té una mida d'1".

* DEFINICIÓ: Broadcasting És un mecanisme que usa Numpy, que permet fer operacions aritmètiques entre arrays amb diferents       shapes, però compatibles

### *Casos en que no hi ha problema per fer operacions aritmètiques amb arrays - NO actua el Broadcasting* 

* a) Quan tinc arrays amb igual shape i size (i per tant tenen el mateix número de dimensions)

*Per exemple*


In [16]:
arr1 = np.array([[1, 2], [3, 4], [5, 6]])
arr2 = np.array([[1, 2], [3, 4], [5, 6]])

In [17]:
print(arr1.shape)
print(arr1.size)

(3, 2)
6


In [18]:
print(arr2.shape)
print(arr2.size)

(3, 2)
6


In [19]:
arr1 + arr2

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [20]:
arr1 * arr2

array([[ 1,  4],
       [ 9, 16],
       [25, 36]])

* b) Quan tenim qualsevol array i un escalar

In [21]:
arr1 = np.array([[1, 2], [3, 4], [5, 6]])
x = 5

In [22]:
arr1 + x

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [23]:
arr1 * x

array([[ 5, 10],
       [15, 20],
       [25, 30]])

### *Casos en que SÍ actua el Broadcasting*

*El Broadcasting actua d'acord amb les següents regles:*

1.- Si els 2 arrays tenen diferent número de dimensions, el shape de la que té menys dimensions és reomplert amb "1"'s per l'esquerra fins homologar el seu número de dimensions amb l'altre array.

2.- Si el shape dels dos arrays no coincideixen en alguna dimensió, l'array amb shape  igual a "1" en aquest adimensió "s'estira" per coincidir amb el shape de l'altre array

3.- Si en alguna dimensió els sizes no coincideixen i cap dels dos és "1", donarà error perquè no són compatibles.

*Primer crearem  np.arrays amb  diferents shapes i dimensions per generar els exemples de diferents casos*

In [24]:
a = np.array([[1, 2], [3, 4], [5, 6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
b = np.array([1, 2, 3])
b

array([1, 2, 3])

In [26]:
c = np.array([1, 2])
c

array([1, 2])

In [27]:
d = np.array([[10], [20], [30]])
d

array([[10],
       [20],
       [30]])

In [28]:
print(a.shape)
print(a.ndim)

(3, 2)
2


In [29]:
print(b.shape)
print(b.ndim)

(3,)
1


In [30]:
print(c.shape)
print(c.ndim)

(2,)
1


In [31]:
print(d.shape)
print(d.ndim)

(3, 1)
2


* INTENTEM SUMAR A + B 


In [32]:
a + b

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

+ Estudiem per qué ens dóna error:
    
    + Mirem els Shapes:
        + a.shape() = (3, 2)
        + b.shape() = (3,)
    
    + Mirem regla 1.L'array b té menys dimensions.Per tant es reomple amb uns per l'esquerra:
        + a.shape() = (3, 2)
        + b.shape() = (1, 3) 
        
    + I ara veiem que per la regla 2, la primera dimensió de b és "estirada" per coincidir amb la de a.
        + a.shape() = (3, 2)
        + b.shape() = (3, 3) 
        
    + Finalment per la regla 3, veiem que els sizes finals no coincideixen (size final de a = 2 i size final de b = 3) 
      i cap dels 2 és "1".
    
      Per tant donarà error perquè els arrays NO són compatibles. 
        
        
        

* INTENTEM MULTIPLICAR A * C

In [33]:
a * c

array([[ 1,  4],
       [ 3,  8],
       [ 5, 12]])

+ Estudiem per qué ha funcionat el Broadcasting:
    
    + Mirem els Shapes:
        + a.shape() = (3, 2)
        + c.shape() = (2,)
    
    + Mirem regla 1.L'array c té menys dimensions.Per tant es reomple amb uns per l'esquerra:
        + a.shape() = (3, 2)
        + c.shape() = (1, 2) 
        
    + I ara veiem que per la regla 2, la primera dimensió de c és "estirada" per coincidir amb la de a.
        + a.shape() = (3, 2)
        + c.shape() = (3, 2) 
        
    + Finalment per la regla 3, veiem que queden amb igual shape (internament ho fa numpy).I els sizes finals coincideixen (els dos són = 2)
    
      Per tant l'operació aritmètica es pot fer  perquè els arrays són compatibles. 

* INTENTEM SUMAR A + D

In [34]:
b + d

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

Estudiem per qué ha funcionat el Broadcasting:

Mirem els Shapes:

b.shape() = (3,)
d.shape() = (3, 1)
Mirem regla 1.L'array d té menys dimensions.Per tant es reomple amb uns per l'esquerra:

b.shape() = (1, 3)
d.shape() = (3, 1)

I ara veiem que per la regla 2, la primera dimensió de b és "estirada" per coincidir amb la de d.

b.shape() = (3, 3)
d.shape() = (3, 1)

I també per la regla 2, la segona  dimensió de d és "estirada" per coincidir amb la de b.

b.shape() = (3, 3)
d.shape() = (3, 3)

Finalment per la regla 3, veiem que queden amb igual shape (internament ho fa numpy).I els sizes finals coincideixen (els dos són = 3)

Per tant l'operació aritmètica es pot fer perquè els arrays són compatibles.

### *EXERCICI 5*

+ Utilitza la Indexació per extreure els valors d'una columna i una fila de la matriu. I suma els seus valors.

In [54]:
arr = np.round(10*np.random.rand(4, 4))
arr

array([[ 6.,  1.,  5.,  6.],
       [ 4.,  0., 10.,  4.],
       [ 6.,  4.,  8.,  5.],
       [ 6.,  7.,  8.,  8.]])

* *Extreiem els valors de la tercera columna i després els sumem.*

In [55]:
arr[ : ,2]

array([ 5., 10.,  8.,  8.])

In [56]:
arr[ : ,2].sum()

31.0

*Extreiem els valors de la segona fila i després els sumem.*

In [57]:
arr[1]

array([ 4.,  0., 10.,  4.])

In [58]:
arr[1].sum()

18.0

### *EXERCICI 6*

* Mask la matriu anterior, realitzeu un càlcul booleà vectoritzat, agafant cada element i comprovant si es divideix uniformement per quatre
* Això retorna una matriu de mask de la mateixa forma amb els resultats elementals del càlcul.


In [59]:
import numpy.ma as ma

In [60]:
arr

array([[ 6.,  1.,  5.,  6.],
       [ 4.,  0., 10.,  4.],
       [ 6.,  4.,  8.,  5.],
       [ 6.,  7.,  8.,  8.]])

In [61]:
mask = (arr%4 == 0)

In [62]:
ma_arr = ma.masked_array(arr, mask)

In [63]:
ma_arr

masked_array(
  data=[[6.0, 1.0, 5.0, 6.0],
        [--, --, 10.0, --],
        [6.0, --, --, 5.0],
        [6.0, 7.0, --, --]],
  mask=[[False, False, False, False],
        [ True,  True, False,  True],
        [False,  True,  True, False],
        [False, False,  True,  True]],
  fill_value=1e+20)

In [64]:
print(ma_arr)

[[6.0 1.0 5.0 6.0]
 [-- -- 10.0 --]
 [6.0 -- -- 5.0]
 [6.0 7.0 -- --]]


### *EXERCICI 7*

* A continuació, utilitzeu aquesta màscara per indexar a la matriu de números original. Això fa que la matriu perdi la seva forma original, reduint-la a una dimensió, però encara obteniu les dades que esteu cercant.

In [65]:
arr[mask]

array([4., 0., 4., 4., 8., 8., 8.])